name: dbsetupmate

services:

  database-15:
    image: "postgres:15"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGDATA: /pgdata
      POSTGRES_DB: ${POSTGRESQL_DB_NAME:-postgres}
      POSTGRES_USER: ${POSTGRESQL_ADMIN_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD:-dbsetupmate}
    ports:
      - "127.0.0.1:5415:5432"
    volumes:
      - dbsetupmate-pg15-db:/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_ADMIN_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dbsetupmate-network

  database-16:
    image: "postgres:16"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGDATA: /pgdata
      POSTGRES_DB: ${POSTGRESQL_DB_NAME:-postgres}
      POSTGRES_USER: ${POSTGRESQL_ADMIN_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD:-dbsetupmate}
    ports:
      - "127.0.0.1:5416:5432"
    volumes:
      - dbsetupmate-pg16-db:/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_ADMIN_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dbsetupmate-network

  database-17:
    image: "postgres:17"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGDATA: /pgdata
      POSTGRES_DB: ${POSTGRESQL_DB_NAME:-postgres}
      POSTGRES_USER: ${POSTGRESQL_ADMIN_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD:-dbsetupmate}
    ports:
      - "127.0.0.1:5417:5432"
    volumes:
      - dbsetupmate-pg17-db:/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_ADMIN_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dbsetupmate-network

  database-18:
    image: "postgres:18"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGDATA: /pgdata
      POSTGRES_DB: ${POSTGRESQL_DB_NAME:-postgres}
      POSTGRES_USER: ${POSTGRESQL_ADMIN_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD:-dbsetupmate}
    ports:
      - "127.0.0.1:5418:5432"
    volumes:
      - dbsetupmate-pg18-db:/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_ADMIN_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dbsetupmate-network

volumes:
  dbsetupmate-pg15-db:
  dbsetupmate-pg16-db:
  dbsetupmate-pg17-db:
  dbsetupmate-pg18-db:
  dbsetupmate-pg19-db:

networks:
  dbsetupmate-network: