version: '3'

vars:
  VENV_DIR: ".venv"

includes:
    git: taskfiles/Taskfile_git.yml
    pc: taskfiles/Taskfile_pre_commit.yml

tasks:

  default:
    desc: lists all tasks
    silent: true
    cmds:
      - task --list-all
      - echo ""
      - echo "Example usage-> 'task check-virtualenv'"

  check-virtualenv:
    desc: checks Python's virtualenv activation
    aliases: [cv]
    silent: true
    run: once
    cmds:
      - echo "Check existence of a virtual directory-> {{.VENV_DIR}}"
      - test -d {{.VENV_DIR}}
      - echo -n "Check if virtual environment is active-> " && python -c "import sys; print('virtualenv is active' if sys.prefix != sys.base_prefix else 'virtualenv is NOT active')"
      - python -c "import sys; exit(1 if sys.prefix == sys.base_prefix else 0)"
      - python --version

  generate-ssl:
    desc: Generate self-signed SSL certificates
    deps: [check-virtualenv]
    silent: true
    dir: src
    cmds:
      - python cli.py generate-ssl

  export-openapi:
    desc: Export OpenAPI as `openapi.yml` file
    deps: [check-virtualenv]
    silent: true
    dir: src
    cmds:
      - python cli.py export-openapi

  test:
    desc: Run tests with pytest
    deps: [check-virtualenv]
    silent: true
    dir: src
    cmds:
      - pytest

  serve:
    env:
       PYTHONDONTWRITEBYTECODE: '1'
       ENV_FILE_NAME: '{{.USER_WORKING_DIR}}\dev-docker.env'
    vars:
       APP_HOST: 127.0.0.1
       APP_PORT: 8001
    desc: runs fastapi server
    dir: src
    aliases: [s]
    silent: true
    deps: [check-virtualenv, generate-ssl]
    cmds:
      - echo "Run FastAPI on -> {{.APP_HOST}}:{{.APP_PORT}}"
      - uvicorn app.server:app --reload --host={{.APP_HOST}} --port={{.APP_PORT}} --ssl-keyfile ./.configs/key.pem --ssl-certfile ./.configs/cert.pem
